Change copyright
siemens/CtrlppCheck pull request #45
Opened 2023-10-09 18:36 UTC by mPokornyETM

2023-10-12 10:48 UTC, dhoegerlETM requested changes
Generally speaking: why include the functions "updateCopyright" and "formatCode" directly into the executeTests.cmd script? I would appreciate to have an own e.g. "handleCtrlCode" script for those functions.

2023-10-12 10:48 UTC, dhoegerlETM commented on WinCC_OA_Test/executeTests.cmd
> +REM Chnage Copyright information
```suggestion
REM Change copyright information
```

2023-10-12 10:48 UTC, dhoegerlETM commented on WinCC_OA_Test/readme.md
> +-changeCopyright, change copyright entries to correct year for whole ctrl code - inclusive ctrl tests (default disabled)
```suggestion
-changeCopyright, change copyright entries to correct year for all ctrl code - including ctrl tests (default disabled)
```

2023-10-12 10:48 UTC, dhoegerlETM commented on WinCC_OA_Test/Projects/TfCustomizedQG/scripts/copyright.ctl
> +      throwError(makeError("", PRIO_INFO, ERR_CONTROL, 0, "Can not change file", ctrlFile.getPath()));
```suggestion
      throwError(makeError("", PRIO_INFO, ERR_CONTROL, 0, "Cannot change file", ctrlFile.getPath()));
```

2023-10-12 11:18 UTC, mPokornyETM commented
> Generally speaking: why include the functions "updateCopyright" and "formatCode" directly into the executeTests.cmd script? I would appreciate to have an own e.g. "handleCtrlCode" script for those functions.

I am inspired by mvn usage (Java) and want to spare duplicated lines (or complex batcscripts struct). Whwn we want provide more solutions here, I will care about that.

2023-10-12 11:23 UTC, dhoegerlETM commented
> > Generally speaking: why include the functions "updateCopyright" and "formatCode" directly into the executeTests.cmd script? I would appreciate to have an own e.g. "handleCtrlCode" script for those functions.
> 
> I am inspired by mvn usage (Java) and want to spare duplicated lines (or complex batcscripts struct). Whwn we want provide more solutions here, I will care about that.

Understand, but then we must rename the tool from executeTests.cmd to something more general, e.g. executeCommands or batchAutomate or executeBatch.

2023-10-12 12:43 UTC, mPokornyETM commented
> > > Generally speaking: why include the functions "updateCopyright" and "formatCode" directly into the executeTests.cmd script? I would appreciate to have an own e.g. "handleCtrlCode" script for those functions.
> > 
> > 
> > I am inspired by mvn usage (Java) and want to spare duplicated lines (or complex batcscripts struct). Whwn we want provide more solutions here, I will care about that.
> 
> Understand, but then we must rename the tool from executeTests.cmd to something more general, e.g. executeCommands or batchAutomate or executeBatch.

OK, I will thing about that, and provide some better name.

2023-10-15 17:48 UTC, mPokornyETM commented
As discussed there is new PR where the tools has been splitted. Therefor may be this one closed

2023-10-15 17:48 UTC, closed without merging

2023-10-15 17:50 UTC, mPokornyETM commented
Only to be precise: See #47