Issue 71: Updated path in Doubleclick section line 3 of QG_History.pnl
siemens/CtrlppCheck pull request #82
Opened 2023-11-09 07:51 UTC by cbv08

Please see issue #71. 
It seems in pre-release version 1.0.2 the path to where the reports where outputed was changed, however the panel for reading them was not. This bugfix resolves that by updating the QG_History.pnl to include the new path.

Before bug:
![Bugfix_71_Before](https://github.com/siemens/CtrlppCheck/assets/147402639/c7df8d0d-4730-470f-896d-71cf92119b05)

After bug:
![Bugfix_71_After](https://github.com/siemens/CtrlppCheck/assets/147402639/6b4080cd-7a16-48a2-9b8a-c190ed47f877)

@mPokornyETM

2023-11-09 08:15 UTC, mPokornyETM commented
Hi, pls paste the screenshot with from working panel. not from changes. I see the changes in the  PR as well. But I want to see, that the panel works now ;-) thx

2023-11-09 08:30 UTC, cbv08 commented
Haha sorry, that makes a lot more sense :D 

Before:
<img width="594" alt="Bugfix_71_Result_Before" src="https://github.com/siemens/CtrlppCheck/assets/147402639/f0b65a89-1725-4fb7-a9f7-f261127ceb05">
After: 
<img width="724" alt="Bugfix_71_ResultAfter" src="https://github.com/siemens/CtrlppCheck/assets/147402639/518b0005-dd87-4931-97ef-9240309051a0">

2023-11-09 10:52 UTC, mPokornyETM commented
My proposal for title:

Cannot open reports in ctrl-editor

2023-11-09 14:41 UTC, dhoegerlETM commented on WinCCOA_QualityChecks/panels/vision/QualityChecks/QG_History.pnl
> +  string fileName = this.cellValueRC(row, \"_resDir\") + \"QgTestVersion\\\\_Results\";
```suggestion
  string fileName = this.cellValueRC(row, \"_resDir\") + \"QgTestVersion/_Results\";
```
Consider Linux clients.

2023-11-09 14:42 UTC, dhoegerlETM requested changes
Please verify my suggestion and update accordingly.

2023-11-10 07:57 UTC, dhoegerlETM approved these changes

2023-11-10 08:00 UTC, merged

2023-11-10 08:02 UTC, mPokornyETM commented
Pleasedo not merge it. See related PR #82

2023-11-10 08:06 UTC, dhoegerlETM commented
> Pleasedo not merge it. See related PR #82

Please explain in more detail - we are already in PR #82...

2023-11-10 11:43 UTC, mPokornyETM commented
sorry I mean #89